### ISSUE TITLE
feat: add tests

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#70] opened 2023-08-28 08:29 UTC
Most of the current listings do not have tests. Adding tests would ensure that we have not left any logic errors that could confuse readers later on.

We need to add atleast simple integration tests for all contracts. Unit tests can be added for more complex contracts.

- Integration tests are tests that deploy the contract and interact with it's provided interface. They should be placed on a separate file/module `tests.cairo`.

- Unit tests do not have to deploy the contract and use the interface. Unit tests can use mocked implementation or state to test only one specific feature. They should be placed on the same file as the example (and hidden in the book using `ANCHOR`).

You do not have to add tests to all missing listings at once.

See [this](https://starknet-by-example.voyager.online/ch00-15-contract-testing.html) as a reference.

Please open a PR per example.

**Comment by ebbieaden** [comment] 2023-08-28 21:21
I will be working on this

**Comment by petersdt** [comment] 2024-05-22 20:15
hi @julio4 can I add more test?

**Comment by NueloSE** [comment] 2024-05-22 20:20
hi @julio4 can i jump on this ?

**Comment by CollinsC1O** [comment] 2024-05-23 01:46
hi @julio4 I will love to work on this

**Comment by julio4** [comment] 2024-05-23 02:23
@petersdt @NueloSE @CollinsC1O Thank you for your interest.
Currently, all chapter0 examples are tested. You can pick any listings without tests and list it here to be assigned to it.
You can take a look at #179 #181 #182 as examples.

**Comment by No-bodyq** [comment] 2024-05-23 10:43
Hey @julio4  can i work on components_dependencies

**Comment by the-first-elder** [comment] 2024-05-24 11:12
i can work on this

**Comment by julio4** [comment] 2024-05-24 11:27
> i can work on this

You need to specify 1-3 tests you want to work on it. Only complete tests will be accepted!

**Comment by NueloSE** [comment] 2024-05-24 12:15
> @petersdt @NueloSE @CollinsC1O Thank you for your interest. Currently, all chapter0 examples are tested. You can pick any listings without tests and list it here to be assigned to it. You can take a look at #179 #181 #182 as examples.

@julio4 can i work on [components](https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/components/src/countable.cairo)

**Comment by petersdt** [comment] 2024-05-24 13:01
can i work on [smart Vault](https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/simple_vault/src/simple_vault.cairo)

**Comment by the-first-elder** [comment] 2024-05-24 13:11
> > i can work on this
> 
> You need to specify the 1-3 tests you want to work on it. Only complete tests will be accepted!

i can work on  [switchable](https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/components/src/switchable.cairo) and [token](https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/erc20/src/token.cairo)

**Comment by julio4** [comment] 2024-05-26 08:01
@NueloSE , @petersdt OK!
@the-first-elder ok for token. Switchable is part of components assigned to @NueloSE currently.

**Comment by CollinsC1O** [comment] 2024-05-26 15:54
Hi @julio4 I will love to work on cairo_cheatsheet

**Comment by LamsyA** [comment] 2024-05-27 14:58
Hi @julio4 I would like to work on [simple_vault.cairo
](https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/simple_vault/src/simple_vault.cairo)
kindly assign it to me.

**Comment by the-first-elder** [comment] 2024-05-27 19:39
I can work on [upgradeable contracts](https://github.com/NethermindEth/StarknetByExample/tree/main/listings/applications/upgradeable_contract/src)

**Comment by Timilehin-bello** [comment] 2024-05-28 01:11
@julio4 I'm interested in writing the test for [SimpleVault](https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/simple_vault/src/simple_vault.cairo) contract. I've gone through the contract code and here are the test cases I'll be handling.

What I'll Test:
Deposit Function:

I will Check the share calculation on deposit.
I will ensure transfer_from is called correctly.
I will verify user balance and total supply updates.

Withdraw Function:

I will check token amount calculation on withdrawal.
I will ensure transfer is called correctly.
I will also verify user balance and total supply updates.

Edge Cases:

Depositing when total supply is zero.
Withdrawing with different share values.
Handling rounding errors.


Some of the example cases I'll work on:

Initial deposit should set correct shares.
Multiple deposits should calculate shares based on current supply/balance.
Full withdrawals should return the correct token amount.
Partial withdrawals should update balances correctly.


I think this should cover everything needed to make sure the SimpleVault works correctly. Let me know if I can take this on. Thank you.

**Comment by Timilehin-bello** [comment] 2024-05-28 01:37
@julio4 I've gone through the upgradable contract and  I can work on it. Please can you kindly assign it to me. Thank you

**Comment by julio4** [comment] 2024-05-28 08:11
> Hi @julio4 I will love to work on cairo_cheatsheet

Exceptionally, we will not add tests for the cairo cheatsheet section

**Comment by julio4** [comment] 2024-05-28 08:26
> @julio4 I've gone through the upgradable contract and I can work on it. Please can you kindly assign it to me. Thank you

Ok! @the-first-elder, let's finish `token` tests and you can work on another just after!

**Comment by Timilehin-bello** [comment] 2024-05-28 11:15
> @julio4 I've gone through the upgradable contract and I can work on it. Please can you kindly assign it to me. Thank you

@julio4 I don't know if it's fine for me to work on it since @the-first-elder is working on something else.

As I mention in my previous message here,  I've gone through the upgradable contract and I know I can work on it. Please can you kindly assign it to me. I will make sure to complete the task on time. Thank you

**Comment by NueloSE** [comment] 2024-05-29 11:14
[go to google](www.google.com)

**Comment by petersdt** [comment] 2024-05-29 12:19
> Hi @julio4 I would like to work on [simple_vault.cairo ](https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/simple_vault/src/simple_vault.cairo) kindly assign it to me.

hi @julio4 @LamsyA i have already been assigned https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/simple_vault/src/simple_vault.cairo and am making a PR soon

**Comment by saimeunt** [comment] 2024-05-30 10:35
Hey @julio4 is there any tests left I can work on? Maybe Constant Product AMM since OZ#953 has been fixed now.
https://github.com/NethermindEth/StarknetByExample/blob/main/listings/applications/constant_product_amm/src/tests.cairo#L41

**Comment by LamsyA** [comment] 2024-06-01 17:17
Hello @julio4 
I have added test to simple_vault contract this is the [PR](https://github.com/NethermindEth/StarknetByExample/pull/206)

**Comment by nemealfaro** [comment] 2024-06-28 22:11
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-by-example).

### My background and how it can be leveraged
Hi, I'm Nemesis Alfaro from Costa Rica, i'm a system engineer.
I love  to learn and practice about different tecnologies.
I'm hard-working, constant and curious person
This would be my first contribution on the platform, in order to gain more knowledge and improve in the area.

### How I plan on tackling this issue
First, i would like carefully read the request and be in  contact with you for more infomation.
Then i would to further investigate about the options to solve the issue

**Comment by julio4** [comment] 2024-07-01 02:20
> Hi, I'm Nemesis Alfaro from Costa Rica, i'm a system engineer. ...
> 

Thank you for your interest! Please take a look at the [contributing guide](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md) to get started.

**Comment by nemealfaro** [comment] 2024-07-01 06:31
Thank you for the opportunity, I will review it and if I have any questions, I will contact you

**Comment by julio4** [comment] 2024-07-01 07:24
New missing tests: `simple_account`

**Comment by od-hunter** [comment] 2024-07-01 07:45
i'm up for it @julio4

**Comment by Ternder001** [comment] 2024-07-20 08:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-by-example).

### My background and how it can be leveraged
My recent focus in Ethereum-Solidity and Starknet-Cairo has significantly deepened my understanding of web3 technologies, positioning me well to contribute to innovative projects in the blockchain space. As an alumnus of Web3Bridge, where I received training in Solidity and Cairo, I have developed a solid foundation in these technologies. I am eager to contribute to open-source projects within the Starknet ecosystem, and I am particularly excited about the opportunity to make meaningful contributions to this project. Given the chance, I am committed to delivering my best work and leveraging my skills to drive success.

### How I plan on tackling this issue
To approach the task of adding integration and unit tests to the Starknet by Example collection, we need a structured plan.

First, set up the testing environment by ensuring that all necessary tools and libraries are installed. This includes Cairo, Starknet CLI, and the Starknet testing framework, such as pytest. Organize your repository to accommodate both the contract examples and their respective tests, perhaps by creating separate directories for contracts and tests.

Next, thoroughly review each contract example to understand its functionality. Identify the key features that need testing and determine the main scenarios to be tested, which includes both integration tests and unit tests.

For integration tests, create a tests.cairo file in a dedicated tests directory for each example. Write test cases that deploy the contract and assert successful deployment. Additionally, write tests that interact with the contract's methods to verify the expected outcomes, simulating real-world use cases. An example of such a test involves deploying the contract and calling its methods, then asserting that the responses are as expected.

For unit tests, add them within the same file as the example for more complex contracts. These tests can be hidden in the book using anchors if necessary. Use mocked implementations or states to isolate and test specific features of the contract. An example unit test involves mocking a specific function or state and asserting the expected behavior.

Once the tests are written, create a new branch for each example you're adding tests to. Add and commit the changes with a descriptive message, then push the branch to your repository and open a PR with a clear description of the changes made.

Ensure that each PR undergoes a thorough code review to confirm that the tests are comprehensive and accurate. Make any necessary changes based on feedback received during the review process, and merge the PRs once they are approved.

To maintain quality, set up a CI pipeline, such as GitHub Actions or GitLab CI, to automatically run tests on every push or PR. This ensures that all tests pass before any changes are merged into the main branch.

By following this structured approach, you can systematically add integration and unit tests to the Starknet by Example collection, ensuring each contract is well-tested and reliable.

**Comment by Giri-Aayush** [comment] 2024-07-27 09:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-by-example).

### My background and how it can be leveraged
I am a solidity developer and migrating to shift to being a cairo developer

### How I plan on tackling this issue
First find the logic to solving the problem and one by implement things by reading the documentation for the language.

**Comment by EmmanuelAR** [comment] 2024-08-12 18:31
heyyyy @julio4 is this still available? any function to test? let me know

**Comment by livinalt** [comment] 2024-10-01 10:36
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-by-example).

### My background and how it can be leveraged
Hi my name is Jeremiah Samuel. I am a frontend and blockchain developer. I build web solutions and interested in building blockchain infrastructures. I am hardworking and focused

This is my first application for contributing and would be looking forward to be granted  that opportunity to gain more experience.



### How I plan on tackling this issue
To begin, I would await briefing on the contracts in need of unit testing. After that I would proceed to write the test, submit and wait for your review and feedback which would determine the next course of action. Your feedback is my quality assurance guiding me in the rest of the tests.

**Comment by julio4** [comment] 2024-10-03 05:37
@livinalt @EmmanuelAR and others... No need to apply on OnlyDust platform. Just explore listings and find one that have no tests, and implement tests for atleast the most important use cases.

**Comment by livinalt** [comment] 2024-10-04 15:45
Thanks for the heads up @julio4. I'll check out the listings

**Comment by Lukman-01** [comment] 2024-10-04 16:29
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-by-example).

### My background and how it can be leveraged
My name Abdulyekeen Lukman, I am smart contract developer with 2 years experience  in smart contract using solidity. I attended the just concluded starknet basecamp x where I learnt about cairo and starknet blockchain. I graduated with distintion(Cum Laude) from the basecamp and my team project was one of the leading projects at the end of build camp. I have writen some starknet smart contract using cairo, I will be glad to contribute to the ecosystem. 

### How I plan on tackling this issue
My Approach:

Tests identify and prevent any logic errors, I will add tests for the existing contracts. At a minimum, I will include integration tests for all contracts, and unit tests for more complex ones. These tests will cover the core functionalities of the contracts, ensuring that all tests pass. I will add them progressively, starting with key contracts rather than all listings at once.

**Comment by zleypner** [comment] 2024-10-08 01:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-by-example).

### My background and how it can be leveraged
I’m a front-end developer with +3 years of experience, and I would love 
to make my first contribution to this project. I'm excited to take
on this issue to challenge myself, and contribute to the project's success.
I'm also a member of the Dojo Coding community CR.
I’ll first review the existing project architecture and infrastructure requirements to ensure I have a complete understanding of what is needed for Starknet by Example


### How I plan on tackling this issue
I’ll start by adding integration tests for each contract, deploying them and interacting with their interfaces. I’ll place these in a tests.cairo file. For more complex contracts, I’ll add unit tests that focus on specific features without deploying the contract, using mock implementations. These unit tests will be placed in the same file as the contract and hidden with ANCHOR. I’ll submit one PR per contract example, gradually adding tests to ensure proper coverage without overwhelming the project.

**Comment by jaiminRaiyani** [comment] 2024-11-04 04:50
Can I take this from here?

**Closed** 2024-11-20 03:43 UTC
Labels: good first issue
